/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator_Stack;

import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ITLAB1-PC05-STUDENT
 */
public class Calculator extends javax.swing.JFrame {
   
   private Stack<Double> stack;
   
    public Calculator() {
        initComponents();
        
        Stack<Double> stack = new Stack<>();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        ButtonPanelNum1 = new javax.swing.JPanel();
        one1 = new javax.swing.JButton();
        four1 = new javax.swing.JButton();
        seven1 = new javax.swing.JButton();
        two1 = new javax.swing.JButton();
        five1 = new javax.swing.JButton();
        eight1 = new javax.swing.JButton();
        three1 = new javax.swing.JButton();
        nine1 = new javax.swing.JButton();
        six1 = new javax.swing.JButton();
        equalbutton1 = new javax.swing.JButton();
        clear1 = new javax.swing.JButton();
        zero1 = new javax.swing.JButton();
        backPanelArithmetic1 = new javax.swing.JPanel();
        addbutton1 = new javax.swing.JButton();
        substractButton1 = new javax.swing.JButton();
        DivisionButton1 = new javax.swing.JButton();
        multiplyButton1 = new javax.swing.JButton();
        backPanelInput1 = new javax.swing.JPanel();
        inputBox1 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        push = new javax.swing.JButton();
        pop = new javax.swing.JButton();
        Peek = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(51, 51, 51));
        MainPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 102), new java.awt.Color(0, 102, 153), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        MainPanel.setForeground(new java.awt.Color(51, 51, 51));

        ButtonPanelNum1.setBackground(new java.awt.Color(102, 102, 102));
        ButtonPanelNum1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.orange));
        ButtonPanelNum1.setForeground(new java.awt.Color(51, 51, 51));

        one1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        one1.setText("1");
        one1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.orange, java.awt.Color.darkGray));
        one1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one1ActionPerformed(evt);
            }
        });

        four1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        four1.setText("4");
        four1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.orange, java.awt.Color.darkGray));
        four1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four1ActionPerformed(evt);
            }
        });

        seven1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        seven1.setText("7");
        seven1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.orange, java.awt.Color.darkGray));
        seven1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven1ActionPerformed(evt);
            }
        });

        two1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        two1.setText("2");
        two1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.orange, java.awt.Color.darkGray));
        two1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two1ActionPerformed(evt);
            }
        });

        five1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        five1.setText("5");
        five1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.orange, java.awt.Color.darkGray));
        five1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five1ActionPerformed(evt);
            }
        });

        eight1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        eight1.setText("8");
        eight1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.orange, java.awt.Color.darkGray));
        eight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eight1ActionPerformed(evt);
            }
        });

        three1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        three1.setText("3");
        three1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.orange, java.awt.Color.darkGray));
        three1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three1ActionPerformed(evt);
            }
        });

        nine1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        nine1.setText("9");
        nine1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.orange, java.awt.Color.darkGray));
        nine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nine1ActionPerformed(evt);
            }
        });

        six1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        six1.setText("6");
        six1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.orange, java.awt.Color.darkGray));
        six1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six1ActionPerformed(evt);
            }
        });

        equalbutton1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        equalbutton1.setText("=");
        equalbutton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.orange, java.awt.Color.darkGray));
        equalbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalbutton1ActionPerformed(evt);
            }
        });

        clear1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        clear1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ITLAB1-PC05-STUDENT\\Pictures\\bin (1).png")); // NOI18N
        clear1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.orange, java.awt.Color.darkGray));
        clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });

        zero1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        zero1.setText("0");
        zero1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.orange, java.awt.Color.darkGray));
        zero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero1ActionPerformed(evt);
            }
        });

        backPanelArithmetic1.setBackground(new java.awt.Color(153, 153, 153));
        backPanelArithmetic1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.orange));

        addbutton1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        addbutton1.setText("+");
        addbutton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.orange, java.awt.Color.darkGray));
        addbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbutton1ActionPerformed(evt);
            }
        });

        substractButton1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        substractButton1.setText("-");
        substractButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.orange, java.awt.Color.darkGray));
        substractButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substractButton1ActionPerformed(evt);
            }
        });

        DivisionButton1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        DivisionButton1.setText("/");
        DivisionButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.orange, java.awt.Color.darkGray));
        DivisionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionButton1ActionPerformed(evt);
            }
        });

        multiplyButton1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        multiplyButton1.setText("*");
        multiplyButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.orange, java.awt.Color.darkGray));
        multiplyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backPanelArithmetic1Layout = new javax.swing.GroupLayout(backPanelArithmetic1);
        backPanelArithmetic1.setLayout(backPanelArithmetic1Layout);
        backPanelArithmetic1Layout.setHorizontalGroup(
            backPanelArithmetic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelArithmetic1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(addbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(substractButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(DivisionButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(multiplyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        backPanelArithmetic1Layout.setVerticalGroup(
            backPanelArithmetic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelArithmetic1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(backPanelArithmetic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(substractButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DivisionButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backPanelInput1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.orange));

        inputBox1.setBackground(new java.awt.Color(51, 51, 51));
        inputBox1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        inputBox1.setForeground(new java.awt.Color(255, 255, 255));
        inputBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.orange));

        javax.swing.GroupLayout backPanelInput1Layout = new javax.swing.GroupLayout(backPanelInput1);
        backPanelInput1.setLayout(backPanelInput1Layout);
        backPanelInput1Layout.setHorizontalGroup(
            backPanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelInput1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backPanelInput1Layout.setVerticalGroup(
            backPanelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelInput1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ButtonPanelNum1Layout = new javax.swing.GroupLayout(ButtonPanelNum1);
        ButtonPanelNum1.setLayout(ButtonPanelNum1Layout);
        ButtonPanelNum1Layout.setHorizontalGroup(
            ButtonPanelNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelNum1Layout.createSequentialGroup()
                .addGroup(ButtonPanelNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backPanelArithmetic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ButtonPanelNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ButtonPanelNum1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(backPanelInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ButtonPanelNum1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(one1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(two1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(three1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ButtonPanelNum1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(four1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(five1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(six1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(equalbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ButtonPanelNum1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(seven1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(eight1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(nine1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(zero1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        ButtonPanelNum1Layout.setVerticalGroup(
            ButtonPanelNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelNum1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(backPanelInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(backPanelArithmetic1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ButtonPanelNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(one1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(ButtonPanelNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(five1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ButtonPanelNum1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(ButtonPanelNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(four1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(six1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equalbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(ButtonPanelNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eight1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ButtonPanelNum1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(ButtonPanelNum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seven1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nine1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zero1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        t5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        t5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.lightGray));

        t2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.lightGray));

        t1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.lightGray));

        t3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        t3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.lightGray));
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        t4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        t4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.lightGray));

        push.setBackground(new java.awt.Color(255, 153, 51));
        push.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        push.setForeground(new java.awt.Color(255, 255, 255));
        push.setText("Push");
        push.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
        push.setOpaque(false);
        push.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pushActionPerformed(evt);
            }
        });

        pop.setBackground(new java.awt.Color(255, 153, 51));
        pop.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        pop.setForeground(new java.awt.Color(255, 255, 255));
        pop.setText("Pop");
        pop.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
        pop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popActionPerformed(evt);
            }
        });

        Peek.setBackground(new java.awt.Color(255, 153, 51));
        Peek.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        Peek.setForeground(new java.awt.Color(255, 255, 255));
        Peek.setText("Peek");
        Peek.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
        Peek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(push, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(pop, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Peek, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ButtonPanelNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(push, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(Peek, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ButtonPanelNum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void handleNumberButtonClick(int number) {
    // Convert the number to string and display it in inputBox1
    inputBox1.setText(inputBox1.getText() + number); // Append the number
}

     
    private void one1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one1ActionPerformed
        handleNumberButtonClick(1);
    }//GEN-LAST:event_one1ActionPerformed

    private void four1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four1ActionPerformed
        handleNumberButtonClick(4);
    }//GEN-LAST:event_four1ActionPerformed

    private void seven1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven1ActionPerformed
        handleNumberButtonClick(7);
    }//GEN-LAST:event_seven1ActionPerformed

    private void two1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two1ActionPerformed
        handleNumberButtonClick(2);
    }//GEN-LAST:event_two1ActionPerformed

    private void five1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five1ActionPerformed
        handleNumberButtonClick(5);
    }//GEN-LAST:event_five1ActionPerformed

    private void eight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eight1ActionPerformed
        handleNumberButtonClick(8);
    }//GEN-LAST:event_eight1ActionPerformed

    private void three1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three1ActionPerformed
        handleNumberButtonClick(3);
    }//GEN-LAST:event_three1ActionPerformed

    private void nine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nine1ActionPerformed
        handleNumberButtonClick(0);
    }//GEN-LAST:event_nine1ActionPerformed

    private void six1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six1ActionPerformed
        handleNumberButtonClick(6);
    }//GEN-LAST:event_six1ActionPerformed

    private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ActionPerformed
        stack.clear(); // Clear the stack
        inputBox1.setText(" "); // Clear the display
    }//GEN-LAST:event_clear1ActionPerformed

    private void zero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero1ActionPerformed
        handleNumberButtonClick(0);
    }//GEN-LAST:event_zero1ActionPerformed

    private void addbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbutton1ActionPerformed
                                         
    try {
        // I-split ang text sa inputBox1 gamit ang delimiter (space o comma)
        String[] numbersStr = inputBox1.getText().split("[ ,]+");
        
        // Check kung pila na ka numbers ang anaa sa t1-t5
        int currentCount = 0;

        if (!t1.getText().isEmpty()) currentCount++;
        if (!t2.getText().isEmpty()) currentCount++;
        if (!t3.getText().isEmpty()) currentCount++;
        if (!t4.getText().isEmpty()) currentCount++;
        if (!t5.getText().isEmpty()) currentCount++;

        // Kung puno na ang lima ka fields, ipakita ang notification
        if (currentCount >= 5) {
            JOptionPane.showMessageDialog(this, "Puno na ang mga fields! Dili na makadugang.");
            return; // Undangan ang process
        }

        // Loop aron ma-add ang mga numero
        for (String numberStr : numbersStr) {
            double number = Double.parseDouble(numberStr);
            
            // Shift values upwards
            t5.setText(t4.getText());
            t4.setText(t3.getText());
            t3.setText(t2.getText());
            t2.setText(t1.getText());
            t1.setText(String.valueOf(number)); // Set the new number to t1
        }

        // Clear the input field for new input
        inputBox1.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Palihug isul ang valid nga mga numero sa input box.");
    }
    }//GEN-LAST:event_addbutton1ActionPerformed

    private void substractButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substractButton1ActionPerformed

         try {
        double num1 = t1.getText().isEmpty() ? 0 : Double.parseDouble(t1.getText());
        double num2 = t2.getText().isEmpty() ? 0 : Double.parseDouble(t2.getText());
        double num3 = t3.getText().isEmpty() ? 0 : Double.parseDouble(t3.getText());
        double num4 = t4.getText().isEmpty() ? 0 : Double.parseDouble(t4.getText());
        double num5 = t5.getText().isEmpty() ? 0 : Double.parseDouble(t5.getText());

        double difference = num1 - num2 - num3 - num4 - num5;

        // Display the result in t5
        t5.setText(String.valueOf(difference));

        // Optionally, push the result onto the stack
        stack.push(difference);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter valid numbers in all fields.");
    }
    }//GEN-LAST:event_substractButton1ActionPerformed

    private void DivisionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionButton1ActionPerformed

    }//GEN-LAST:event_DivisionButton1ActionPerformed

    private void multiplyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButton1ActionPerformed

    }//GEN-LAST:event_multiplyButton1ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void pushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pushActionPerformed
        try {
            // Get user input from inputBox
            double value = Double.parseDouble(inputBox1.getText());

            // Check if all fields are filled
            if (!inputBox1.getText().isEmpty() &&
                !t1.getText().isEmpty() &&
                !t2.getText().isEmpty() &&
                !t3.getText().isEmpty() &&
                !t4.getText().isEmpty() &&
                !t5.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Cannot push: All fields are full!");
                inputBox1.setText("");  // Clear jTextField4 if unable to push
                return;
            }
            // Shift values upwards
            t1.setText(t2.getText());
            t2.setText(t3.getText());
            t3.setText(t4.getText());
            t4.setText(t5.getText());
            t5.setText(String.valueOf(value));  // Display new value in jTextField5

            // Push the value onto the stack
            stack.push(value);  // Only the value pushed from jTextField4 should go to the stack

            // Clear the input field for new input
            inputBox1.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number.");
        }
    }//GEN-LAST:event_pushActionPerformed

    private void popActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popActionPerformed
        // Check if the stack is empty (by checking if jTextField3 is empty)
        if (t5.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nothing to pop: Stack is empty.");
            return;
        }

        // Get the current top value from jTextField3 to show in the message
        double poppedValue = Double.parseDouble(t5.getText());

        // Show a message with the popped value
        JOptionPane.showMessageDialog(this, "Popped element: " + poppedValue);

        // Shift values downwards
        t4.setText(t5.getText()); // Move value from jTextField2 to jTextField3 (new top)
        t3.setText(t4.getText());
        t2.setText(t3.getText());
        t1.setText(t2.getText()); // Move value from jTextField1 to jTextField2
        inputBox1.setText("");
    }//GEN-LAST:event_popActionPerformed

    private void PeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeekActionPerformed
        // Check if jTextField5 is empty before trying to peek
        if (t5.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Stack is empty, nothing to peek.");
        } else {
            // Safely parse the top value from jTextField5
            double topValue = Double.parseDouble(t5.getText());
            // Display the top value in a JOptionPane message
            JOptionPane.showMessageDialog(this, "Top item of the stack: " + topValue);
        }
    }//GEN-LAST:event_PeekActionPerformed

    private void equalbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalbutton1ActionPerformed
     try {
        // Kuhaon ang mga numero gikan sa t1 hangtod t5
        double num1 = t1.getText().isEmpty() ? 0 : Double.parseDouble(t1.getText());
        double num2 = t2.getText().isEmpty() ? 0 : Double.parseDouble(t2.getText());
        double num3 = t3.getText().isEmpty() ? 0 : Double.parseDouble(t3.getText());
        double num4 = t4.getText().isEmpty() ? 0 : Double.parseDouble(t4.getText());
        double num5 = t5.getText().isEmpty() ? 0 : Double.parseDouble(t5.getText());

        // I-add ang mga numero
        double sum = num1 + num2 + num3 + num4 + num5;

        // I-display ang resulta sa t5
        inputBox1.setText(String.valueOf(sum)); // Display the sum in inputBox1
        JOptionPane.showMessageDialog(this, "Sum: " + sum); // Show the sum in a message dialog

        // I-clear ang tanan fields
        inputBox1.setText("");
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Palihug isul ang valid nga mga numero sa t1 hangtod t5.");
    }
}

private void pushNumbersFromInput() {
    try {
        // I-split ang text sa inputBox1 gamit ang delimiter (space o comma)
        String[] numbersStr = inputBox1.getText().split("[ ,]+");
        
        // Check kung pila na ka numbers ang anaa sa t1-t5
        int currentCount = 0;

        if (!t1.getText().isEmpty()) currentCount++;
        if (!t2.getText().isEmpty()) currentCount++;
        if (!t3.getText().isEmpty()) currentCount++;
        if (!t4.getText().isEmpty()) currentCount++;
        if (!t5.getText().isEmpty()) currentCount++;

        // Kung puno na ang lima ka fields, ipakita ang notification
        if (currentCount >= 5) {
            JOptionPane.showMessageDialog(this, "Puno na ang mga fields! Dili na makadugang.");
            return; // Undangan ang process
        }

        // Loop aron ma-add ang mga numero
        for (String numberStr : numbersStr) {
            double number = Double.parseDouble(numberStr);
            
            // Shift values upwards
            t5.setText(t4.getText());
            t4.setText(t3.getText());
            t3.setText(t2.getText());
            t2.setText(t1.getText());
            t1.setText(String.valueOf(number)); // Set the new number to t1
        }

        // Clear the input field for new input
        inputBox1.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Palihug isul ang valid nga mga numero sa input box.");
    }
    
    }//GEN-LAST:event_equalbutton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanelNum1;
    private javax.swing.JButton DivisionButton1;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton Peek;
    public javax.swing.JButton addbutton1;
    private javax.swing.JPanel backPanelArithmetic1;
    private javax.swing.JPanel backPanelInput1;
    private javax.swing.JButton clear1;
    private javax.swing.JButton eight1;
    private javax.swing.JButton equalbutton1;
    private javax.swing.JButton five1;
    private javax.swing.JButton four1;
    private javax.swing.JTextField inputBox1;
    private javax.swing.JButton multiplyButton1;
    private javax.swing.JButton nine1;
    private javax.swing.JButton one1;
    private javax.swing.JButton pop;
    private javax.swing.JButton push;
    private javax.swing.JButton seven1;
    private javax.swing.JButton six1;
    private javax.swing.JButton substractButton1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JButton three1;
    private javax.swing.JButton two1;
    private javax.swing.JButton zero1;
    // End of variables declaration//GEN-END:variables


   
}
